### PR TITLE
Allow webthing server to be restarted from outside

### LINKED ISSUE #21: Ability to restart the webthing server
Currently the start method of server takes the ownership of `self`, and also blocks the thread. I'm not able to restart the server programmatically. Is it possible to make it non blocking?

My use case is - whenever there is new sensor added to mysensors network, I want to restart WoT server in order to make the new thing appear in the API list.

### PR DESCRIPTION
**Pull request by tsathishkumar**
Moved server creation to start method and created blocking
run method to allow external control of server actor.

Fixes #21

### CODE REVIEW

**Comment by tsathishkumar** [comment]
@mrstegeman I have removed the stop method as well, because `start` already consumes `self` and there is no way stop can be called from outside. Let me know if my understanding is wrong.

**Comment by tsathishkumar** [comment]
Addresses #21

**Comment by tsathishkumar** [comment]
@mrstegeman what do you think about this feature?

**Comment by mrstegeman** [comment]
@tsathishkumar I'm find with the concept, generally speaking, but I have 2 thoughts:

1. I don't like that there is a `start()` method **and** a `run()` method. To me, those have nearly the same meaning. Are there some better function names we could use?
2. After calling `run()`, your program is still blocked, so how does this change anything? Can you give me a small example of how this fixes things?

**Comment by tsathishkumar** [comment]
> 1. I don't like that there is a start() method and a run() method. To me, those have nearly the same meaning. Are there some better function names we could use?

Maybe `create` and `start`.

> After calling run(), your program is still blocked, so how does this change anything? Can you give me a small example of how this fixes things?

I take the address and pass to another thread and kill server in that thread. Below is a sample code:

```
        let addr = server.start();
        thread::spawn(move || {
            handle_sensor_additions(
                &mut things_clone,
                new_sensor_receiver,
                set_message_sender_clone,
                addr,
            );
        });

        server.run();
```

Within `handle_sensor_additions` method I send kill signal to the addr.

```
things.push(thing);
addr.do_send(signal::Signal(signal::SignalType::Term));
```

Working example can be found [here](https://github.com/tsathishkumar/MySController-rs/blob/master/src/wot/mod.rs#L199-L209)

**Comment by mrstegeman** [comment]
1. I like `create` and `start` better. Let's go with that.
2.  I see now. Would you want to include a simple example in the `examples` folder that people could use?

**Comment by mrstegeman** [comment]
As an alternative, did you consider this:

1. Change the library to start the server in a thread, so that developers don't need to do that themselves.
2. Make `stop` do what it is supposed to, i.e. send the term signal to the thread.

**Comment by tsathishkumar** [comment]
> Change the library to start the server in a thread, so that developers don't need to do that themselves.

I considered this first, but the problem is, we need to block it one place or another. I couldn't proceed forward with that approach. Another thing is `self.system.run();` this consumes `self` so we can't use self after this point.

I'll do the refactoring to use `create` and `start` and add example.

**Comment by tsathishkumar** [comment]
Should the minor version increased for this change?

**Comment by mrstegeman** [comment]
Yes, I'll include this in 0.9. I typically do a new release when we have some spec changes that require me to make changes in all the webthing libraries. Until then, feel free to just use the git repo as your dependency.

**Pull request merged**
